# Site wide configuration

title:            My Journal
locale:           en_US
url:


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Mirzalazuardi Hermawan
  avatar: bio-photo.jpg
  bio: "Sharing is Caring"
  email: mirzalazuardi@gmail.com
  disqus-shortname: mirzalazuardigithubpages
  twitter: mirzalazuardi
  facebook: mirzalazuardi.hermawan
  google:
    plus: MirzalazuardiHermawan1
    analytics: UA-65639723-4
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: mirzalazuardi
  stackoverflow: 3093351/luckymeerza
  #linkedin: mirzalazuardi
  xing: #username
  instagram: luckymeerza
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
